name: Terraform plan Difference
on:
  pull_request:
    branches:
      - master

jobs:
# Update 'Job name' and 'terraform_directory' as needed based on the module structure.
  point-to-site-with-certificate-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/point-to-site-with-certificate'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  site-to-site-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/site-to-site'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  point-to-site-with-ad-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/point-to-site-with-ad'
      target_branch: 'master'
